Merge Akulbako/refactor core autotests branch to master
luxteam/jobs_test_core pull request #40
Opened 2020-11-12 11:59 UTC by testpassword

2020-11-23 15:25 UTC, Speedwag00n approved these changes

2020-11-23 15:27 UTC, epozine approved these changes
Waiting for QA approve

2020-11-23 16:27 UTC, Piromancer requested changes
Возникло несколько вопросов
1. Отображается две версии коры, это на стороне разработки или на нашей? 2.1.7 2.1.6
2. https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_WX7100-Windows/Results/Core/AA_Test_Scene_Northstar64/report.html?searchText=AA_BlackmanHarris_1.rpr
Известно почему ничего не отображается? Судя по логу что-то должно было отрендерить. Меня еще смущает, что этот кейс использует конфиг из другого кейса
C:\JN\WS\RadeonProRenderCore_Test@2\Work\Results\Core\AA_Test_Scene_Northstar64>"C:\JN\WS\RadeonProRenderCore_Test@2\rprSdk\RprsRender64.exe" "C:\TestResources\CoreAssets\AA_Test_Scene_Northstar64\AA_BlackmanHarris_1.rpr" "C:\JN\WS\RadeonProRenderCore_Test@2\Work\Results\Core\AA_Test_Scene_Northstar64\cfg_AA_BlackmanHarris_2.rpr.json" 
3. Что означают эти ошибки?
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_WX7100-Windows/Results/Core/launcher.engine.log
[2020-11-19 13:03:35,698] #ERROR  [F:simpleRender.py L:69] >> Failed to copy baseline c:/TestResources/rpr_core_autotests_baselines\AOV_Northstar64\AOVTest.rprindirect.diffuse_RPR.json


[2020-11-19 13:35:48,852] #ERROR  [F:simpleRender.py L:238] >> Can't create img stub: [Errno 2] No such file or directory: 'C:\\JN\\WS\\RadeonProRenderCore_Test@2\\Work\\Results\\Core\\Performance_Hybrid\\Color\\acca_restaurant/acca_restaurant.rpr.png'
[2020-11-19 13:35:48,853] #ERROR  [F:simpleRender.py L:398] >> [Errno 2] No such file or directory: 'C:\\JN\\WS\\RadeonProRenderCore_Test@2\\Work\\Results\\Core\\Performance_Hybrid\\acca_restaurant/acca_restaurant.rpr_RPR.json'
[2020-11-19 13:35:48,853] #ERROR  [F:simpleRender.py L:399] >> Traceback: Traceback (most recent call last):
  File "C:\JN\WS\RadeonProRenderCore_Test@2\jobs/Scripts/simpleRender.py", line 395, in main
    prepare_cases(args, test_cases, render_platform)
  File "C:\JN\WS\RadeonProRenderCore_Test@2\jobs/Scripts/simpleRender.py", line 240, in prepare_cases
    with open(os.path.join(args.output, case_name + CASE_REPORT_SUFFIX), 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\JN\\WS\\RadeonProRenderCore_Test@2\\Work\\Results\\Core\\Performance_Hybrid\\acca_restaurant/acca_restaurant.rpr_RPR.json'

[2020-11-19 13:35:49,184] #ERROR  [F:compareByJSON.py L:268] >> Broken report: Expecting value: line 1 column 1 (char 0)
[2020-11-19 13:35:49,184] #ERROR  [F:compareByJSON.py L:290] >> Can't get input data: Expecting value: line 1 column 1 (char 0)

4. Почему везде пишет что таймаут превышен?
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RXVEGA-OSX/Results/Core/AA_Test_Scene_Tahoe64/report.html
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RXVEGA-OSX/Results/Core/CPU_Northstar64/report.html
5. У нас всегда GPU RAM Diff был с такой точностью? Нужно убавить точность до 3 знаков после запятой
![image](https://user-images.githubusercontent.com/44932328/99987562-ae3b6c00-2dc1-11eb-8534-de89bedf6355.png)

2020-11-23 16:28 UTC, Piromancer commented on README.md
> +    ***You should use the specific scenes which defined in `test_cases.json` files in `jobs/Tests/` folders.***
Put `CoreAssets` scenes placed in `C:/TestResources`
Тут видимо оговорка, Put `CoreAssets` scenes in `C:/TestResources`

2020-11-23 16:33 UTC, Piromancer commented
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RadeonVII-Ubuntu18/Results/Core/Performance_Northstar64/report.html
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RX5700XT-Windows/Results/Core/Performance_Hybrid/report.html
Я не могу открыть отчет групп Performance_*, 404 ошибка

2020-11-23 16:39 UTC, Piromancer commented on jobs/Tests/AOV_Northstar64/test_cases.json
> +            },
А есть смысл так делать? Если целью было сделать возможность скипать определенные АОВ то именно так и нужно сделать, а сейчас я так понимаю эти тесты просто исчезнут. Иначе - это ведь прописано в конфиге, дублировать в автотесты смысла нет

2020-11-23 16:46 UTC, Piromancer commented on jobs/Tests/CPU_Northstar64/test_cases.json
> +        "case": "CPU-Dual-Test.rpr"
Не могу точно сказать используется в отчетах сейчас case или scene. Называть кейсы так же как сцены нет смысла, раз уж рефакторим может уберем заодно постфиксы ".rpr"? Понятно, что бейзлайны надо будет обновить скорее всего, но считаю что лучше так все же сделать. И если вдруг вы согласны, проследите, пожалуйста, чтобы не было кейсов с одинаковыми именами (как в CPU/Dual Hybrid/NorthStar/Tahoe), чтобы у нас наконец то нормально работала Compare вкладка в коре. Или хотя бы протестите, пожалуйста, что в отчетах юзается case и мы сами изменим именование

2020-11-26 09:36 UTC, Speedwag00n commented
> Возникло несколько вопросов

1. Уже была схожая ситуация (она даже в данный момент в текущем мастере у разработки). Для разных движков используется разная версия коры.
2. Была опечатка в конфигурации тестов
3. Ошибки конфигурации
4. Было пофикшено ранее, но фулл прогон был без фикса
5. Добавил округление vram метрик в отчетах (см. ссылку на ПР в jobs_launcher в описании)

2020-11-26 09:37 UTC, Speedwag00n commented on jobs/Tests/AOV_Northstar64/test_cases.json
> +            },
Переписали. Список берется теперь из json с конфигурацией для сцен

2020-11-26 09:38 UTC, Speedwag00n commented on jobs/Tests/CPU_Northstar64/test_cases.json
> +        "case": "CPU-Dual-Test.rpr"
Переименовали. Теперь Compare вкладка работает

2020-11-26 09:38 UTC, Speedwag00n commented
Ссылка на отчет в описании обновлена

2020-11-26 12:59 UTC, Piromancer requested changes
Меня почти все устраивает, только проблему с этим кейсом не устранили. А также я заметил, что GPU RAM diff работает только в гибриде (в остальных движках там просто 0), да и там неправильно. К ПРу не относится, но наверное нужно удалить эту колонку (или как минимум скрыть по умолчанию)
https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RadeonVII-Ubuntu18/Results/Core/AA_Test_Scene_Northstar64/report.html?searchText=AA_BlackmanHarris_1.rpr

2020-11-26 13:42 UTC, Speedwag00n commented
> Меня почти все устраивает, только проблему с этим кейсом не устранили. А также я заметил, что GPU RAM diff работает только в гибриде (в остальных движках там просто 0), да и там неправильно. К ПРу не относится, но наверное нужно удалить эту колонку (или как минимум скрыть по умолчанию)
> https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/48/Test_20Report/AMD_RadeonVII-Ubuntu18/Results/Core/AA_Test_Scene_Northstar64/report.html?searchText=AA_BlackmanHarris_1.rpr

Ты смотрел старый отчет. Сейчас этот кейс исправлен
https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/880/Test_20Report/

2020-11-26 13:44 UTC, Speedwag00n commented
Колонку с GPU RAM diff уберу в отдельном ПРе

2020-11-26 14:28 UTC, Piromancer approved these changes

2020-11-26 14:41 UTC, merged