Change repository makeReport to jobs_launcher makeReport
luxteam/jobs_test_core pull request #46
Opened 2020-12-04 21:34 UTC by testpassword

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1942
### Purpose
* Make a common `makeReport.py` script for all tests repositories.
### Effect of change
* Now repositories with autotests calls unified `makeReport.py` from jobs_launcher.
### Technical steps
- [x] Change all calls in `test.job-manifest.xml` for all tests.
- [x] Remove old script.
### Dependencies
* https://github.com/luxteam/jobs_launcher/pull/140
### Jenkins Builds
* Core: https://rpr.cis.luxoft.com/job/DevRadeonProRenderCoreManual/86/

2020-12-09 11:16 UTC, Speedwag00n approved these changes

2020-12-10 08:10 UTC, Piromancer requested changes
Убери, пожалуйста, изменения jobs_launcher

2020-12-10 14:02 UTC, Piromancer approved these changes

2020-12-10 14:03 UTC, Speedwag00n approved these changes

2020-12-16 19:17 UTC, merged